# ==============================================================================
# Ansible Hosts Inventory: Food Delivery Partner Portal
# ==============================================================================

[local]
localhost ansible_connection=local

[staging]
staging-node-01 ansible_host=192.168.1.110 ansible_user=ubuntu env=staging

[production]
azure-vm ansible_host=20.2.68.23 ansible_user=ubuntu env=production domain_name=api.dpa.yashparmar.in

[staging:vars]
deployment_environment=staging
spring_profile=staging

[production:vars]
deployment_environment=production
spring_profile=prod

[partner_portal:children]
staging
production
local
